#!/usr/bin/env bash
# this script show all process
# Must show all processes, for all users, including those which might not have a TTY
# Display a user-oriented format
# Show process hierarchy

ps aux