#!/usr/bin/env bash
#fizzbuzz

x=1
while [ $x -lt 101 ]
do
    if [[ $(( $x % 3 )) -eq 0 && $(( $x % 5 )) -eq 0 ]]
    then
        echo "FizzBuzz"
    elif [[ $(( $x % 3 )) -eq 0 ]]
    then
        echo "Fizz"
    elif [[ $(( $x % 5 )) -eq 0 ]]
    then
        echo "Buzz"
    else
        echo $x
    fi
    let x+=1
done