#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:

Hour=0

while [ $Hour -lt 13 ]
do
    echo "Hour: $Hour"
    Minute=1
    while [ $Minute -lt 60 ]
    do
        echo $Minute
        let Minute+=1
    done
    let Hour+=1
done
